# Generated by Django 4.0.4 on 2022-05-03 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='base_Project',
        ),
    ]
