# Generated by Django 4.0.4 on 2022-05-03 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_project_base_project'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='base_Project',
            new_name='Project',
        ),
    ]
