# Generated by Django 4.0.4 on 2022-05-11 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_project_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='user_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
